version: '3'
services:
  database:
    container_name: "bike-sns-db-container"
    image: mysql:5.7
    command: mysqld_safe --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-grant-tables
    volumes:
      - ./db/conf:/etc/mysql/conf.d
      - ./db/init:/docker-entrypoint-initdb.d
      - bike_sns_db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: bike_sns
      MYSQL_DATABASE: bike_sns
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: "Asia/Tokyo"
    networks:
      - bike_sns_net
  webapp:
    restart: always
    container_name: "bike-sns-webapp-container"
    build: ./webapp
    working_dir: /go/src
    ports: 
      - '11323:1323'
    volumes:
      - ./webapp/:/go/src
    expose:
      - '1323'
    command: sleep infinity
    tty: true
    depends_on:
      - database
    networks:
      - bike_sns_net
  batch:
    restart: always
    container_name: bike-sns-batch-container
    build: ./scraping
    working_dir: /python/src
    ports:
      - '11324:1324'
    volumes:
      - ./scraping/:/python/src
    expose:
      - '1324'
    command: sleep infinity
    tty: true
    depends_on:
      - database
    networks:
      - bike_sns_net
networks:
  bike_sns_net:
    driver: bridge

volumes:
  bike_sns_db_volume: