version: '3'
services:
  database:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
      - '33307:3307'
    expose: 
      - '3307'
    environment:
      MYSQL_ROOT_PASSWORD: bike_sns
      MYSQL_DATABASE: bike_sns
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: "Asia/Tokyo"
    volumes:
      - ../db/conf:/etc/mysql/conf.d
      - ../db/init:/docker-entrypoint-initdb.d
  webapp:
    build: ./golang
    working_dir: /go/src
    ports: 
      - '11323:1323'
    volumes:
      - ../webapp/:/go/src
    expose:
      - '1323'
    command: sleep infinity
  batch:
    build: ./python
    working_dir: /python/src
    ports:
      - '11324:1324'
    volumes:
      - ../scraping/:/python/src
    expose:
      - '1324'
    command: sleep infinity